spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/raylee?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    #password: root
  activemq:
    broker-url: failover:tcp://127.0.0.1:61616
    user: raylee
    password: root
    reptile-queue: list
    save-queue: details
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000
logging:
  level:
    root: info