spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leilee?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    dbcp2:      driver-class-name: com.mysql.cj.jdbc.Driver